schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='
    goVersion = '1.18'

  [mod.'github.com/adrg/xdg']
    version = 'v0.5.3'
    hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='
    goVersion = '1.19'

  [mod.'github.com/amarbel-llc/purse-first/libs/dewey']
    version = 'v0.3.1'
    hash = 'sha256-JenpYLuvp7oAgmrgEJbW6YEEljCJeApCQrJZou2tEo4='
    goVersion = '1.26'

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='
    goVersion = '1.16'

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.1'
    hash = 'sha256-d/NjM/ybG+bGRRRMMcjbPCFGFS5noZRMaL05Ix5r/II='
    goVersion = '1.24.2'

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.0'
    hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='
    goVersion = '1.18'

  [mod.'github.com/charmbracelet/log']
    version = 'v0.4.2'
    hash = 'sha256-3w1PCM/c4JvVEh2d0sMfv4C77Xs1bPa1Ea84zdynC7I='
    goVersion = '1.19'

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.6'
    hash = 'sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI='
    goVersion = '1.24.2'

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.15'
    hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='
    goVersion = '1.24.2'

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='
    goVersion = '1.24.0'

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.9.0'
    hash = 'sha256-9CNyTZPSncKQ7Y0my9DR4WYXDjtDHYNL512D691WDAM='
    goVersion = '1.18'

  [mod.'github.com/clipperhouse/stringish']
    version = 'v0.1.1'
    hash = 'sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg='
    goVersion = '1.18'

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.5.0'
    hash = 'sha256-Men4JLhiuEtAx8ZSzId5ciRWhud68o3k/B48ppwyxkM='
    goVersion = '1.18'

  [mod.'github.com/cpuguy83/go-md2man/v2']
    version = 'v2.0.6'
    hash = 'sha256-wJnHgp+NPchXkR71ARLMjo4VryzgGkz2tYWPsC+3eFo='
    goVersion = '1.12'

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.9.0'
    hash = 'sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g='
    goVersion = '1.17'

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.0'
    hash = 'sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg='
    goVersion = '1.17'

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.4.0'
    hash = 'sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE='
    goVersion = '1.18'

  [mod.'github.com/gobwas/glob']
    version = 'v0.2.3'
    hash = 'sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='
    goVersion = '1.21'

  [mod.'github.com/google/shlex']
    version = 'v0.0.0-20191202100458-e7afc7fbc510'
    hash = 'sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM='
    goVersion = '1.13'

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='
    goVersion = '1.18'

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='
    goVersion = '1.12'

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='
    goVersion = '1.15'

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.19'
    hash = 'sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE='
    goVersion = '1.20'

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='
    goVersion = '1.17'

  [mod.'github.com/otiai10/copy']
    version = 'v1.14.1'
    hash = 'sha256-8RR7u17SbYg9AeBXVHIv5ZMU+kHmOcx0rLUKyz6YtU0='
    goVersion = '1.18'

  [mod.'github.com/otiai10/mint']
    version = 'v1.6.3'
    hash = 'sha256-/FT3dYP2+UiW/qe1pxQ7HiS8et4+KHGPIMhc+8mHvzw='
    goVersion = '1.18'

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='
    goVersion = '1.21.0'

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='
    goVersion = '1.18'

  [mod.'github.com/russross/blackfriday/v2']
    version = 'v2.1.0'
    hash = 'sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.11.0'
    hash = 'sha256-PUX8dzJtkD8YDZFNqpHnl4qgb0tE1W/DLnL7V+/d1z4='
    goVersion = '1.23.0'

  [mod.'github.com/sourcegraph/conc']
    version = 'v0.3.1-0.20240121214520-5f936abd7ae8'
    hash = 'sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8='
    goVersion = '1.20'

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='
    goVersion = '1.23.0'

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='
    goVersion = '1.21.0'

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='
    goVersion = '1.15'

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='
    goVersion = '1.12'

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='
    goVersion = '1.23.0'

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='
    goVersion = '1.17'

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='
    goVersion = '1.18'

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='
    goVersion = '1.19'

  [mod.'go.etcd.io/bbolt']
    version = 'v1.4.3'
    hash = 'sha256-ahFku15afu8YNTOAFR7v/MmKyxKhvv+ZwqrgP5lguNQ='
    goVersion = '1.23'

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='
    goVersion = '1.16'

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260410095643-746e56fc9e2f'
    hash = 'sha256-JaDJGLIRoJjjvsg3dgfFuo7XApEJO2V4kUDmd58qTLI='
    goVersion = '1.25.0'

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='
    goVersion = '1.25.0'

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='
    goVersion = '1.25.0'

  [mod.'golang.org/x/term']
    version = 'v0.42.0'
    hash = 'sha256-FCiDvAfq7dgBGQuiDYDFJbj/JPawhrmPF2qdUEftQ1c='
    goVersion = '1.25.0'

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='
    goVersion = '1.25.0'

  [mod.'gopkg.in/check.v1']
    version = 'v1.0.0-20201130134442-10cb98267c6c'
    hash = 'sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs='
    goVersion = '1.11'

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'mvdan.cc/sh/v3']
    version = 'v3.13.1'
    hash = 'sha256-FM+2xpGELZLm4Gc09OE5Z3JeNLPMvzeb1wRcdAIeKy4='
    goVersion = '1.25.0'
