package cmd

import (
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// newGenManCmd implements the hidden `gen-man <dir>` command that emits the
// section-1 man page tree (conformist.1 plus one page per subcommand) from the
// cobra command definitions, per eng-manpages(7) PRINCIPLE 3 (auto-generate the
// CLI reference rather than hand-maintaining a doc/conformist.1.scd that drifts
// from the real flags). It is invoked at build time by the Nix manpages
// derivation (flake.nix); it is not a user-facing command.
//
// The command is Hidden so cobra's doc.GenManTree skips it
// (hidden => !IsAvailableCommand()), keeping it out of both the generated pages
// and `conformist --help`.
func newGenManCmd() *cobra.Command {
	return &cobra.Command{
		Use:    "gen-man <dir>",
		Short:  "Generate section-1 man pages into <dir> (build-time codegen)",
		Args:   cobra.ExactArgs(1),
		Hidden: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			cmd.SilenceUsage = true

			outDir := args[0]
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return fmt.Errorf("failed to create man output dir %q: %w", outDir, err)
			}

			header := &doc.GenManHeader{
				Title:   "CONFORMIST",
				Section: "1",
				Source:  programName,
				Manual:  programName + " manual",
			}

			// Honor SOURCE_DATE_EPOCH so the .TH date is reproducible across Nix
			// builds (the stdenv sets it in the sandbox). Left unset for local
			// runs, where the rendered output is never committed anyway.
			if epoch := os.Getenv("SOURCE_DATE_EPOCH"); epoch != "" {
				if sec, err := strconv.ParseInt(epoch, 10, 64); err == nil {
					t := time.Unix(sec, 0).UTC()
					header.Date = &t
				}
			}

			// Generate from the root command so every subcommand page is emitted.
			root := cmd.Root()
			// Drop the "Auto generated by spf13/cobra" footer for deterministic output.
			root.DisableAutoGenTag = true

			if err := doc.GenManTree(root, header, outDir); err != nil {
				return fmt.Errorf("failed to generate man pages: %w", err)
			}

			return nil
		},
	}
}
